tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up


ports:
  - port: 8000
    onOpen: open-browser
  - port: 3305
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker
